# Generated by Django 2.1.7 on 2019-03-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190307_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='professional',
            field=models.BooleanField(default=False),
        ),
    ]
