# Generated by Django 2.1.7 on 2019-03-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190306_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal_map',
            name='observed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
