# Generated by Django 2.1.7 on 2019-03-08 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190307_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal_map',
            name='duration_input',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal_map',
            name='file_ex_input',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal_map',
            name='file_name_input',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal_map',
            name='file_size_input',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
