# Generated by Django 2.0.13 on 2019-05-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190524_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal_map',
            name='address1',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='animal_map',
            name='address2',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='animal_map',
            name='address3',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='animal_map',
            name='address4',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='animal_map',
            name='address5',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='animal_map',
            name='address6',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
