# Generated by Django 2.1.7 on 2019-03-08 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190308_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal_Sum_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='animal_map',
            name='file_ex_input',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='animal_map',
            name='file_name_input',
            field=models.CharField(max_length=30),
        ),
        migrations.AddField(
            model_name='animal_sum_file',
            name='Animal_map',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.Animal_map'),
        ),
    ]
