# Generated by Django 2.0.13 on 2020-08-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190524_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal_map',
            name='address',
            field=models.CharField(blank=True, choices=[('a', '서울특별시'), ('b', '경기도'), ('c', '강원도'), ('d', '충청북도'), ('e', '충청남도'), ('f', '경상북도'), ('g', '경상남도'), ('h', '전라북도'), ('i', '전라남도'), ('j', '제주도'), ('k', '북한'), ('l', '세종시'), ('m', '인천'), ('n', '대전'), ('o', '울산'), ('p', '대구'), ('q', '부산')], default='a', help_text='address_Level', max_length=1),
        ),
    ]
