# Generated by Django 2.0.13 on 2020-08-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200819_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal_total_info',
            name='classis',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal_total_info',
            name='divisio',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal_total_info',
            name='familia',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal_total_info',
            name='genus',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal_total_info',
            name='kingdom',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal_total_info',
            name='ordo',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal_total_info',
            name='species',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
