# Generated by Django 2.1.7 on 2019-03-08 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190308_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal_map',
            name='file_size_input',
            field=models.IntegerField(null=True),
        ),
    ]
