# Generated by Django 2.0.13 on 2020-08-19 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200819_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal_total_info',
            name='classis',
        ),
        migrations.RemoveField(
            model_name='animal_total_info',
            name='divisio',
        ),
        migrations.RemoveField(
            model_name='animal_total_info',
            name='familia',
        ),
        migrations.RemoveField(
            model_name='animal_total_info',
            name='genus',
        ),
        migrations.RemoveField(
            model_name='animal_total_info',
            name='kingdom',
        ),
        migrations.RemoveField(
            model_name='animal_total_info',
            name='ordo',
        ),
        migrations.RemoveField(
            model_name='animal_total_info',
            name='species',
        ),
    ]
