# Generated by Django 2.0.13 on 2020-08-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200819_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='soundfile',
            field=models.FileField(default=1, upload_to='temporary'),
            preserve_default=False,
        ),
    ]
