# Generated by Django 2.1.7 on 2019-03-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190308_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal_sub_file',
            name='label',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
