# Generated by Django 2.0.13 on 2020-08-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200819_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal_map',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
