# Generated by Django 2.0.13 on 2021-02-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200901_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal_map',
            name='title1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
