# Generated by Django 2.0.13 on 2021-02-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_animal_map_title1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal_map',
            name='title1',
            field=models.CharField(blank=True, default=0, max_length=100),
            preserve_default=False,
        ),
    ]
