# Generated by Django 2.0.13 on 2021-03-08 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20210204_2005'),
        ('blog', '0013_auto_20200831_0204'),
    ]

    operations = [
    ]
