# Generated by Django 2.1.7 on 2019-03-08 06:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Animal_map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=20)),
                ('Latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('Longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('content', models.TextField()),
                ('imagefile', models.FileField(upload_to='img')),
                ('soundfile', models.FileField(upload_to='sound')),
                ('file_size_input', models.IntegerField(null=True)),
                ('file_name_input', models.CharField(max_length=30, null=True)),
                ('file_ex_input', models.CharField(max_length=10, null=True)),
                ('duration_input', models.IntegerField(null=True)),
                ('observed_date', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Animal_Sub_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='subsound')),
                ('label', models.CharField(max_length=30, null=True)),
                ('start_point', models.IntegerField(null=True)),
                ('end_point', models.IntegerField(null=True)),
                ('file_size_input', models.IntegerField(null=True)),
                ('file_name_input', models.CharField(max_length=30, null=True)),
                ('file_ex_input', models.CharField(max_length=10, null=True)),
                ('duration_input', models.IntegerField(null=True)),
                ('Animal_map', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.Animal_map')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('content', models.TextField()),
            ],
        ),
    ]
