# Generated by Django 2.1.5 on 2019-03-06 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190228_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal_map',
            old_name='file',
            new_name='imagefile',
        ),
    ]
