# Generated by Django 2.1.7 on 2019-03-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190307_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal_map',
            name='observed_date',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
