# Generated by Django 2.1.7 on 2019-03-08 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190308_1146'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Animal_Sum_file',
            new_name='Animal_Sub_file',
        ),
    ]
