# Generated by Django 2.1.7 on 2019-03-08 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190308_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal_sub_file',
            name='end_point',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal_sub_file',
            name='file',
            field=models.FileField(default=1, upload_to='subsound'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal_sub_file',
            name='label',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal_sub_file',
            name='start_point',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
