# Generated by Django 2.1.7 on 2019-03-08 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190308_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal_map',
            name='duration_input',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='animal_map',
            name='file_ex_input',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='animal_map',
            name='file_name_input',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='animal_sub_file',
            name='file',
            field=models.FileField(null=True, upload_to='subsound'),
        ),
    ]
