# Generated by Django 2.1.7 on 2019-03-08 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190308_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal_sub_file',
            name='end_point',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='animal_sub_file',
            name='start_point',
            field=models.IntegerField(null=True),
        ),
    ]
