# Generated by Django 2.1.7 on 2019-03-08 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20190308_1541'),
        ('blog', '0014_auto_20190308_1543'),
    ]

    operations = [
    ]
